In [1]:
from keras.models import load_model
import cv2
import numpy as np

model = load_model('convlstm_model_final.h5')

vid = cv2.VideoCapture(0)

category =['NonViolence', 'Violence']

queue=[]
buffer=[]
j=1
i=" "


while (vid.isOpened()):
    ret,frame = vid.read()
    if ret:
        cv2.imshow('frame', frame)
        image = cv2.resize(frame,(90,90))
        #image = frame/255.0
        buffer.append(image)
        if(j%20==0):
            print(j)
            
            sequence = []
            for image in buffer:
                sequence.append(image)
                
            prediction = model.predict(np.expand_dims(sequence, axis=0))
            print(prediction)
            buffer=[]
            sequence=[]
            queue.append(prediction)
            results = np.array(queue).mean(axis=0)
            i = category[np.argmax(results)]
            print('Predicted: '+ i)
        j=j+1
        
        text = "activity: {}".format(i)
        cv2.putText(frame, text, (20, 35), cv2.FONT_HERSHEY_SIMPLEX,1.25, (0, 255, 0), 5) 
        cv2.imshow('frame',frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

vid.release()
cv2.destroyAllWindows()
     

20
[[0.94732654 0.05267344]]
Predicted: NonViolence
40
[[0.94732654 0.05267344]]
Predicted: NonViolence
60
[[0.94732654 0.05267344]]
Predicted: NonViolence
80
[[0.94732654 0.05267344]]
Predicted: NonViolence
100
[[0.94732654 0.05267344]]
Predicted: NonViolence
120
[[0.94732654 0.05267344]]
Predicted: NonViolence
140
[[0.94732654 0.05267344]]
Predicted: NonViolence
160
[[0.94732654 0.05267344]]
Predicted: NonViolence
180
[[0.94732654 0.05267344]]
Predicted: NonViolence
200
[[0.94732654 0.05267344]]
Predicted: NonViolence
220
[[0.94732654 0.05267344]]
Predicted: NonViolence
240
[[0.94732654 0.05267344]]
Predicted: NonViolence
260
[[0.94732654 0.05267344]]
Predicted: NonViolence
280
[[0.94732654 0.05267344]]
Predicted: NonViolence
300
[[0.94732654 0.05267344]]
Predicted: NonViolence
320
[[0.94732654 0.05267344]]
Predicted: NonViolence
340
[[0.94732654 0.05267344]]
Predicted: NonViolence
360
[[0.94732654 0.05267344]]
Predicted: NonViolence
380
[[0.94732654 0.05267344]]
Predicted: NonViolen